name: flood-streamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.0
  - numpy=1.26.0
  - scipy=1.12.0
  - geopandas=0.14.3
  - pip
  - pip:
    - streamlit==1.32.0
    - plotly==5.18.0